name = "bodobako-worker"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "ROOM_DO"
class_name = "RoomDO"

[[durable_objects.bindings]]
name = "REGISTRY"
class_name = "RoomRegistry"

[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["RoomRegistry"]
